[project]
name = "llm-performance-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "adhoc-api>=2.0.4",
    "archytas>=1.3.13",
]
